# FORGE CONFIG (DO NOT REMOVE!)
include forge-conf/lagospadelclub.com/before/*;

server {

    server_name lagospadelclub.com www.lagospadelclub.com;
    server_tokens off;

    root /home/forge/lagospadelclub.com/public;
    index index.html index.htm index.php;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    charset utf-8;

    # FORGE CONFIG (DO NOT REMOVE!)
    include forge-conf/lagospadelclub.com/server/*;

    # Caching for images
    location ~* \.(jpg|jpeg|png|gif|ico|svg|webp)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # Caching for CSS
    location ~* \.(css)$ {
        expires 7d;
        add_header Cache-Control "public, no-transform";
    }

    # Caching for JavaScript
    location ~* \.(js)$ {
        expires 7d;
        add_header Cache-Control "public, no-transform";
    }

    # Caching for fonts
    location ~* \.(woff|woff2|ttf|eot|otf)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico {
        access_log off;
        log_not_found off;
    }

    location = /robots.txt {
        access_log off;
        log_not_found off;
    }

    access_log off;
    error_log /var/log/nginx/lagospadelclub.com-error.log error;

    error_page 404 /index.php;

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php/php8.2-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }

    listen 80;
    listen [::]:80;
}

# FORGE CONFIG (DO NOT REMOVE!)
include forge-conf/lagospadelclub.com/after/*;
